uclouvain/osis-admission

contrib/models/base.py
contrib/models/doctorate.py
tests/contrib/models/test_base.py

OS-107: Configure a new upload repository path

---

api/schema.py
api/serializers/secondary_studies.py
schema.yml

- Needs https://github.com/uclouvain/osis/pull/11347 and vice-versa

Add filefields to high school diplomas

---

contrib/models/cdd_mail_template.py
infrastructure/projet_doctoral/doctorat/epreuve_confirmation/domain/service/notification.py
infrastructure/projet_doctoral/preparation/domain/service/notification.py
infrastructure/projet_doctoral/preparation/domain/service/profil_candidat.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
mail_templates.py
migrations/0044_confirmation_mail_templates.py
tests/api/views/test_approvals.py
tests/api/views/test_project.py
tests/api/views/test_signatures.py
tests/api/views/test_supervision.py
tests/views/config/test_cdd_mail_templates.py
tests/views/doctorate/forms/test_extension_request.py

Needs:
-  https://github.com/uclouvain/osis-mail-template/pull/22

OS-26 Add backoffice admission link in tokens

---

auth/roles/adre.py
auth/roles/cdd_manager.py
contrib/models/cdd_mail_template.py
forms/doctorate/cdd/send_mail.py
infrastructure/projet_doctoral/doctorat/domain/service/historique.py
infrastructure/projet_doctoral/doctorat/domain/service/notification.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templatetags/admission.py
tests/factories/doctorate.py

OS-192 Better historisation of emails 

---

api/schema.py
api/serializers/person.py
ddd/projet_doctoral/preparation/domain/model/_candidat_signaletique.py
ddd/projet_doctoral/preparation/domain/service/profil_candidat.py
ddd/projet_doctoral/preparation/domain/validator/__init__.py
ddd/projet_doctoral/preparation/domain/validator/_should_identification_candidat_etre_completee.py
ddd/projet_doctoral/preparation/domain/validator/exceptions.py
ddd/projet_doctoral/preparation/domain/validator/validator_by_business_action.py
ddd/projet_doctoral/preparation/dtos.py
ddd/projet_doctoral/preparation/test/use_case/read/test_verifier_proposition_service.py
ddd/projet_doctoral/preparation/test/use_case/write/test_soumettre_proposition_service.py
infrastructure/projet_doctoral/preparation/domain/service/in_memory/profil_candidat.py
infrastructure/projet_doctoral/preparation/domain/service/profil_candidat.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
schema.yml
tests/factories/person.py

[OS-184] Modifications related to the identification tabs

---

api/serializers/secondary_studies.py
schema.yml
tests/api/views/test_secondary_studies.py
tests/factories/secondary_studies.py

OS-168: Modifications related to the education tab

---

api/schema.py
api/serializers/secondary_studies.py
schema.yml
tests/api/views/test_secondary_studies.py

[OS-168-with-institute] Use the highschool model for the institute field

---

infrastructure/projet_doctoral/preparation/domain/service/doctorat.py

A passer en même temps que : https://github.com/uclouvain/osis/pull/12608

Fix import of Training dto

---

api/schema.py
api/serializers/curriculum.py
schema.yml
tests/api/views/test_curriculum.py

[OS-196-institute] Add the institute field inside the curriculum api views

---

admin.py
auth/roles/adre.py
auth/roles/ca_member.py
auth/roles/candidate.py
auth/roles/cdd_manager.py
auth/roles/doctorate_reader.py
auth/roles/jury_secretary.py
auth/roles/promoter.py
auth/roles/sceb.py
auth/roles/sic_director.py
auth/roles/sic_manager.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
migrations/0001_initial.py
migrations/0046_doctorate_roles_evolutions.py

- ajout d'un prefix au role pour un meilleur tri des modèles dans l'admin
- ajout de la mixin d'hijack pour faciliter l'hijack des managers CDD, SIC et autres

Hotfix: add hijack button on admission admin

---

api/views/specific_questions.py
api/views/training.py
api/views/training_choice.py
ddd/admission/doctorat/preparation/test/factory/doctorat.py

Update DRF : raise_exception enforced as keyword-only arg

---

exports/admission_archive.py
tests/exports/test_export_pdf.py

Changes after the evolutions of osis-document (0.7)

---

.gitignore
README.md
admin.py
apps.py
models.py
tests.py
urls.py
views.py

Pull request automatique de hotfix/OS-650 vers DEV

[WIP] [hotfix/OS-650 => DEV] Front-office : Le tri et la recherche lors de la sélection du pays n_est pas fonctionnel en langue EN

---

forms/admission/curriculum.py
forms/admission/education.py
infrastructure/admission/domain/service/profil_candidat.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
schema.yml
static/admission/admission.css
templates/admission/forms/bachelor_education.html
templates/admission/forms/curriculum_educational_experience.html
templates/admission/forms/curriculum_experience_year_form.html
templates/admission/general_education/checklist.html
templates/admission/general_education/includes/checklist/parcours.html
templates/admission/general_education/includes/checklist/parcours_row.html
templates/admission/general_education/includes/checklist/previous_experiences.html
templates/admission/general_education/includes/checklist/previous_experiences_access_title_equivalency_form.html
templates/admission/general_education/includes/checklist/previous_experiences_prevent_to_choose_success_modal.html
templates/admission/general_education/tab_layout.html
templates/admission/includes/bootstrap_field_with_tooltip.html
templates/admission/modal/modal.html
templatetags/admission.py
templatetags/enums.py
tests/views/common/detail_tabs/checklist/test_past_experiences.py
views/common/detail_tabs/checklist.py

[OS-709] Improvements and fixes in the past experiences tabs in the checklist

---

ddd/admission/formation_generale/domain/model/enums.py
ddd/admission/formation_generale/domain/model/proposition.py
ddd/admission/formation_generale/domain/validator/_should_informations_checklist_etre_completees.py
ddd/admission/formation_generale/domain/validator/validator_by_business_actions.py
ddd/admission/formation_generale/test/use_case/write/test_envoyer_proposition_a_fac_lors_de_la_decision_facultaire_service.py
ddd/admission/formation_generale/test/use_case/write/test_refuser_admission_par_sic.py
ddd/admission/formation_generale/test/use_case/write/test_refuser_inscription_par_sic.py
ddd/admission/formation_generale/test/use_case/write/test_specifier_informations_acceptation_proposition_par_sic_service.py
templates/admission/general_education/includes/checklist/sic_decision.html
templatetags/admission.py
tests/test_predicates.py
tests/views/common/detail_tabs/checklist/sic_decision/test_approval.py
tests/views/common/detail_tabs/checklist/sic_decision/test_refusal.py

À valider après https://github.com/uclouvain/osis-admission/pull/615

Fix OS-730: Gestion des états & interactions avec le statut global

---

api/views/references.py
contrib/models/base.py
ddd/admission/doctorat/validation/test/use_case/read/test_filtrer_demandes.py
ddd/admission/formation_generale/domain/model/proposition.py
ddd/admission/formation_generale/domain/validator/__init__.py
ddd/admission/formation_generale/domain/validator/_should_informations_checklist_etre_completees.py
ddd/admission/formation_generale/domain/validator/validator_by_business_actions.py
ddd/admission/formation_generale/test/use_case/write/test_modifier_statut_checklist_experience_parcours_anterieur_service.py
ddd/admission/repository/i_proposition.py
ddd/admission/utils.py
exports/admission_archive.py
forms/admission/filter.py
forms/doctorate/cdd/filter.py
infrastructure/admission/formation_generale/domain/service/notification.py
infrastructure/admission/formation_generale/repository/proposition.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/general_education/includes/checklist/choix_formation_form.html
templates/admission/general_education/includes/checklist/fac_decision_send_to_fac_modal.html
templates/admission/general_education/includes/checklist/fac_decision_send_to_sic_modal.html
tests/api/views/test_submission.py
tests/exports/test_export_pdf.py
tests/forms/doctorate/cdd/test_filter.py
tests/views/common/detail_tabs/checklist/test_faculty_decision.py
tests/views/common/detail_tabs/checklist/test_single_past_experience.py
tests/views/test_list.py
views/common/detail_tabs/checklist.py

Release 1.1.1

---

management/commands/process_admission_tasks.py
tests/exports/test_export_pdf.py

Pull request automatique de hotfix/OS-773 vers QA

[hotfix/OS-773 => QA] [Production de document] Process admission tasks

---

management/commands/process_admission_tasks.py
tests/exports/test_export_pdf.py

Pull request automatique de hotfix/OS-773 vers MASTER

Release 1.1.5

---

management/commands/process_admission_tasks.py
tests/exports/test_export_pdf.py

Pull request automatique de hotfix/OS-773 vers DEV

[WIP] [hotfix/OS-773 => DEV] [Production de document] Process admission tasks

---

static/admission/admission.css
templates/admission/document/document_detail.html
templates/admission/general_education/checklist.html

Pull request automatique de hotfix/OS-768 vers QA

[hotfix/OS-768 => QA] Back-office: Checklist > Document utile courant : désynchro entre nom du document, document affiché, et statut de réclamation

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
mail_templates/checklist.py
templates/admission/exports/fac_decision_certificate.html

Pull request automatique de feature/OS-750 vers DEV

[feature/OS-750 => DEV] Back-office: Checklist > Décision de la faculté > PDF accord/refus - retour de test 16/01/2024

---

api/serializers/project.py
schema.yml

Pull request automatique de hotfix/OS-776 vers QA

[hotfix/OS-776 => QA] Front-office: Statuts globaux communicables aux candidats

---

static/admission/mask.js

Pull request automatique de hotfix/OS-759 vers QA

[hotfix/OS-759 => QA] Back-office: Liste des demandes > Numéro de dossier : problème lorsqu_on colle un numéro de dossier

---

templates/admission/general_education/checklist.html
templates/admission/general_education/includes/checklist/sic_decision.html
templates/admission/general_education/includes/checklist/sic_decision_approval_final_form.html
templates/admission/general_education/includes/checklist/sic_decision_refusal_final_form.html
templates/admission/general_education/includes/checklist/sic_decision_refusal_form.html

Pull request automatique de hotfix/OS-770 vers QA

[hotfix/OS-770 => QA] Back-office : Décision SIC > Formulaire invalide après changement de status

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
mail_templates/checklist.py
templates/admission/exports/fac_approval_certificate.html
templates/admission/exports/fac_decision_certificate.html
templates/admission/exports/fac_refusal_certificate.html

Pull request automatique de hotfix/OS-767 vers QA

[hotfix/OS-767 => QA] Back-office: Décision facultaire > Update des pdfs de refus & d_accord facultaire

---

templates/admission/general_education/checklist.html
templates/admission/general_education/includes/checklist/sic_decision.html
templates/admission/general_education/includes/checklist/sic_decision_approval_final_form.html
templates/admission/general_education/includes/checklist/sic_decision_refusal_final_form.html
templates/admission/general_education/includes/checklist/sic_decision_refusal_form.html

Pull request automatique de hotfix/OS-770 vers MASTER

[hotfix/OS-770 => MASTER] Back-office : Décision SIC > Formulaire invalide après changement de status

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
mail_templates/checklist.py
templates/admission/exports/fac_approval_certificate.html
templates/admission/exports/fac_decision_certificate.html
templates/admission/exports/fac_refusal_certificate.html

Pull request automatique de hotfix/OS-767 vers MASTER

[hotfix/OS-767 => MASTER] Back-office: Décision facultaire > Update des pdfs de refus & d_accord facultaire

---

ddd/admission/formation_generale/domain/service/i_historique.py
ddd/admission/formation_generale/use_case/write/specifier_informations_acceptation_proposition_par_sic_service.py
ddd/admission/formation_generale/use_case/write/specifier_motifs_refus_proposition_par_sic_service.py
infrastructure/admission/formation_generale/domain/service/historique.py
infrastructure/admission/formation_generale/domain/service/in_memory/historique.py
infrastructure/admission/formation_generale/handlers.py
infrastructure/admission/formation_generale/handlers_in_memory.py
templates/admission/general_education/includes/checklist/sic_decision.html
tests/views/common/detail_tabs/checklist/sic_decision/test_approval.py
tests/views/common/detail_tabs/checklist/sic_decision/test_approval_final.py
tests/views/common/detail_tabs/checklist/sic_decision/test_dispensation_change.py
tests/views/common/detail_tabs/checklist/sic_decision/test_refusal.py
tests/views/common/detail_tabs/checklist/sic_decision/test_refusal_final.py
views/common/detail_tabs/checklist.py

Pull request automatique de hotfix/OS-769 vers QA

[hotfix/OS-769 => QA] Back-office: En-tête d_une demande > la date du dernier changement de statut global n_est pas toujours à jour 

---

ddd/admission/formation_generale/domain/validator/validator_by_business_actions.py
ddd/admission/formation_generale/test/use_case/write/test_refuser_admission_par_sic.py
ddd/admission/formation_generale/test/use_case/write/test_refuser_inscription_par_sic.py

Pull request automatique de hotfix/OS-774 vers QA

[hotfix/OS-774 => QA] Back-office : Décision SIC > Impossible d_envoyer un refus sans motif (nécessite que OS-762 soit mergé)

---

forms/admission/curriculum.py
tests/views/autocomplete/test_diploma_title.py
views/autocomplete/diploma_title.py

Pull request automatique de hotfix/OS-800 vers DEV

[hotfix/OS-800 => DEV] Afficher le niveau d_étude (SNU ou UNIV) devant l_étude

---

templates/admission/exports/sic_approval_annexe.html
templates/admission/exports/sic_approval_certificate.html
templates/admission/exports/sic_inscription_refusal_certificate.html
templates/admission/exports/sic_refusal_certificate.html

Pull request automatique de hotfix/OS-809 vers QA

[hotfix/OS-809 => QA] Back-office: Décision SIC > Pdfs d_autorisation/refus > Centrer la signature manuscrite

---

auth/predicates/general.py
auth/roles/central_manager.py
auth/roles/program_manager.py
ddd/admission/domain/model/emplacement_document.py
ddd/admission/domain/service/i_historique.py
ddd/admission/formation_generale/commands.py
ddd/admission/formation_generale/domain/model/proposition.py
ddd/admission/formation_generale/test/use_case/write/test_annuler_reclamation_documents_au_candidat_service.py
ddd/admission/formation_generale/use_case/write/__init__.py
ddd/admission/formation_generale/use_case/write/annuler_reclamation_documents_au_candidat_service.py
ddd/admission/repository/i_emplacement_document.py
infrastructure/admission/domain/service/historique.py
infrastructure/admission/domain/service/in_memory/historique.py
infrastructure/admission/formation_generale/handlers.py
infrastructure/admission/formation_generale/handlers_in_memory.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/document/base.html
templates/admission/document/missing_documents.html
templates/admission/document/received_documents.html
templates/admission/document/uclouvain_documents.html
templates/admission/general_education/includes/checklist/sic_decision.html
templates/admission/modal/confirm_modal.html
tests/test_predicates.py
tests/views/common/detail_tabs/test_document.py
views/common/detail_tabs/documents.py

[OS-834] Allow to cancel the documents request

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/document/request_all_documents.html
templates/admission/document/request_all_documents_modal.html

Pull request automatique de hotfix/OS-821 vers QA

[hotfix/OS-821 => QA] Back-office: Réclamation de documents (par SIC et par fac)> Update du mécanisme de génération du mail

---

templates/admission/exports/includes/footer_campus.html
templates/admission/exports/includes/profil_adresse.html
templates/admission/exports/sic_approval_certificate.html

Pull request automatique de hotfix/OS-827 vers QA

[hotfix/OS-827 => QA] Back-office:  Décision SIC > Gain de place pour le pdf d_autorisation

---

infrastructure/admission/formation_generale/domain/service/pdf_generation.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/exports/sic_approval_annexe.html

Pull request automatique de hotfix/OS-826 vers QA

[hotfix/OS-826 => QA] Back-office:  Décision SIC > Autorisation > Signature du recteur sur l_annexe 1

---

ddd/admission/enums/emplacement_document.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
tests/factories/person.py

Pull request automatique de hotfix/OS-859 vers QA

[hotfix/OS-859 => QA] Back-office: Décision SIC > Après envoi de l’autorisation - nom de l’autorisation et de l’annexe 1 dans les documents UCLouvain

---

ddd/admission/enums/emplacement_document.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
tests/factories/person.py

Pull request automatique de hotfix/OS-859 vers DEV

[hotfix/OS-859 => DEV] Back-office: Décision SIC > Après envoi de l’autorisation - nom de l’autorisation et de l’annexe 1 dans les documents UCLouvain

---

templates/admission/general_education/includes/checklist/sic_decision.html
templates/admission/general_education/includes/checklist/sic_decision_approval_final_form.html

Pull request automatique de hotfix/OS-858 vers QA

[hotfix/OS-858 => QA] Back-office: Décision SIC > Autorisation à valider & autorisation > Prévisualisation conditionnelle de l’annexe 1

---

templates/admission/general_education/includes/checklist/sic_decision.html
templates/admission/general_education/includes/checklist/sic_decision_approval_final_form.html

Pull request automatique de hotfix/OS-858 vers DEV

[hotfix/OS-858 => DEV] Back-office: Décision SIC > Autorisation à valider & autorisation > Prévisualisation conditionnelle de l’annexe 1

---

forms/admission/checklist.py
templates/admission/general_education/includes/checklist/sic_decision_approval_form.html
tests/views/common/detail_tabs/checklist/sic_decision/test_approval.py

Pull request automatique de hotfix/OS-856 vers QA

[hotfix/OS-856 => QA] Back-office: Décision SIC > Autorisation à valider > Switch visa (update)

---

forms/admission/checklist.py
templates/admission/general_education/includes/checklist/sic_decision_approval_form.html
tests/views/common/detail_tabs/checklist/sic_decision/test_approval.py

Pull request automatique de hotfix/OS-856 vers DEV

[hotfix/OS-856 => DEV] Back-office: Décision SIC > Autorisation à valider > Switch visa (update)

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
migrations/0155_sic_approval_mail_eu_remove_images.py

Pull request automatique de hotfix/OS-867 vers DEV

[hotfix/OS-867 => DEV] Back-office: Décision SIC > mail d_autorisation pour une admission UE+5 > problèmes de rendu

---

infrastructure/admission/formation_generale/domain/service/pdf_generation.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
tests/views/common/detail_tabs/checklist/sic_decision/test_approval_final.py

Pull request automatique de hotfix/OS-866 vers DEV

[hotfix/OS-866 => DEV] Back-office: Décision SIC > mail d_autorisation pour admission d_un candidat UE+5 > annexe 1 ajoutée aux documents UCLouvain

---

templates/admission/general_education/checklist.html
templates/admission/general_education/includes/checklist/modal-htmx-reload.html
templates/admission/general_education/includes/checklist/previous_experiences.html
templates/admission/general_education/includes/checklist/sic_decision_approval_final_form.html
templates/admission/general_education/includes/checklist/sic_decision_approval_final_modal.html
templates/admission/general_education/includes/checklist/sic_decision_approval_form.html

Pull request automatique de hotfix/OS-868 vers DEV

[hotfix/OS-868 => DEV] Back-office: Décision SIC & Documents à réclamer > Changement de statut de réclamation n_est pas répercuté

---

infrastructure/admission/doctorat/preparation/domain/service/doctorat.py
infrastructure/admission/formation_continue/domain/service/formation.py
infrastructure/admission/formation_generale/domain/service/formation.py

Pull request automatique de hotfix/OS-911 vers QA

[hotfix/OS-911 => QA] Bug: _Je sélectionne une filere et une autre s’affiche à l’enregistrement de l’admission_

---

infrastructure/admission/doctorat/preparation/domain/service/doctorat.py
infrastructure/admission/formation_continue/domain/service/formation.py
infrastructure/admission/formation_generale/domain/service/formation.py

Pull request automatique de hotfix/OS-911 vers DEV

[hotfix/OS-911 => DEV] Bug: _Je sélectionne une filere et une autre s’affiche à l’enregistrement de l’admission_

---

static/admission/clipboard.js
templates/admission/general_education/tab_layout.html
views/common/detail_tabs/debug.py

Pull request automatique de hotfix/OS-893 vers QA

[hotfix/OS-893 => QA] Back-office: En-tête d_une demande > La copie à côté du numéro de dossier référencera un lien plutôt qu_un simple numéro

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
views/common/detail_tabs/checklist.py

Pull request automatique de hotfix/OS-887 vers DEV

[hotfix/OS-887 => DEV] Back-office: Documents utiles de la décision SIC : les documents de la décision fac y seront repris

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
static/admission/AdmissionSelectFilter.js

Pull request automatique de hotfix/OS-879 vers DEV

[hotfix/OS-879 => DEV] Back-office: Décision SIC & Décision fac > Refus > Amélioration ergonomique pour les motifs de refus

---

ddd/admission/formation_generale/domain/model/proposition.py

Pull request automatique de hotfix/OS-876 vers QA

[hotfix/OS-876 => QA] Back-office: Décision SIC & Décision fac > Conserver à la fois le dernier pdf d_autorisation/accord et le dernier pdf de refus

---

templates/admission/general_education/checklist.html

Pull request automatique de hotfix/OS-890 vers DEV

[hotfix/OS-890 => DEV] Back-office: Checklist > Spécificités de la formation : Ajout d_un état _A compléter après inscription_

---

ddd/admission/formation_generale/domain/service/i_pdf_generation.py
ddd/admission/formation_generale/use_case/read/recuperer_pdf_temporaire_decision_sic_service.py
ddd/admission/formation_generale/use_case/write/refuser_admission_par_sic_service.py
ddd/admission/formation_generale/use_case/write/refuser_inscription_par_sic_service.py
infrastructure/admission/formation_generale/domain/service/in_memory/pdf_generation.py
infrastructure/admission/formation_generale/domain/service/pdf_generation.py
infrastructure/admission/formation_generale/handlers.py
infrastructure/admission/formation_generale/handlers_in_memory.py
templates/admission/exports/includes/refusal_footer_campus.html
templates/admission/exports/sic_inscription_refusal_certificate.html
templates/admission/exports/sic_refusal_certificate.html
templatetags/admission.py
tests/templatetags/test_admission.py
tests/views/common/detail_tabs/checklist/sic_decision/test_refusal_final.py
tests/views/common/detail_tabs/test_accounting.py

Pull request automatique de hotfix/OS-913 vers DEV

[hotfix/OS-913 => DEV] Back-office: Décision SIC > pdf de refus > Pied de page _Bruxelles_ pour Saint-Louis & _LLN_ pour les autres campus

---

ddd/admission/formation_generale/domain/model/proposition.py

Pull request automatique de hotfix/OS-876 vers DEV

[hotfix/OS-876 => DEV] Back-office: Décision SIC & Décision fac > Conserver à la fois le dernier pdf d_autorisation/accord et le dernier pdf de refus

---

infrastructure/admission/formation_generale/domain/service/pdf_generation.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
mail_templates/checklist.py
migrations/0147_sic_refusal_mail_template_director.py
migrations/0166_sic_refusal_mail_director_gender.py
migrations/0167_sic_refusal_mail_signature_change.py
templates/admission/details/history.html
templates/admission/exports/includes/sic_certificate_signature.html
templates/admission/exports/sic_approval_certificate.html
templates/admission/exports/sic_inscription_refusal_certificate.html
templates/admission/exports/sic_refusal_certificate.html
templates/admission/includes/lite_admission_list.html
views/common/detail_tabs/checklist.py

Pull request automatique de hotfix/OS-922 vers QA

[hotfix/OS-922 => QA] Back-office: Décision SIC > Autorisation & refus > Mails & pdfs > FR & EN : Adaptations Saint-Louis

---

templates/admission/general_education/checklist.html
templates/admission/general_education/includes/checklist/parcours.html
templates/admission/modal/confirm_modal.html
views/common/form_tabs/curriculum.py

Reverts uclouvain/osis-admission#1100

Revert "[OS-825] CV experiences > redirect to the original checklist and parcours tabs after a deletion or a duplication "

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/empty_template.html
templates/admission/general_education/checklist.html
templates/admission/general_education/includes/checklist/parcours.html
templates/admission/general_education/includes/checklist/parcours_row.html
templates/admission/general_education/includes/checklist/parcours_row_actions_links.html
templates/admission/modal/confirm_modal.html
templatetags/admission.py
tests/utils/test_copy_documents.py
tests/views/common/form_tabs/curriculum/test_educational_experience.py
tests/views/common/form_tabs/curriculum/test_non_educational_experience.py
utils.py
views/common/form_tabs/curriculum.py

Pull request automatique de hotfix/OS-825 vers DEV

[hotfix/OS-825 => DEV] Back-office: Parcours antérieur > Nettoyage du parcours : duplication d_une expérience & ergonomie des boutons

---

infrastructure/admission/formation_generale/domain/service/pdf_generation.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
mail_templates/checklist.py
migrations/0147_sic_refusal_mail_template_director.py
migrations/0163_sic_refusal_mail_director_gender.py
migrations/0167_sic_refusal_mail_signature_change.py
templates/admission/exports/includes/sic_certificate_signature.html
templates/admission/exports/sic_approval_certificate.html
templates/admission/exports/sic_inscription_refusal_certificate.html
templates/admission/exports/sic_refusal_certificate.html
templates/admission/includes/lite_admission_list.html
views/common/detail_tabs/checklist.py

Pull request automatique de hotfix/OS-922 vers DEV

[hotfix/OS-922 => DEV] Back-office: Décision SIC > Autorisation & refus > Mails & pdfs > FR & EN : Adaptations Saint-Louis

---

contrib/models/base.py
ddd/admission/domain/model/emplacement_document.py
ddd/admission/formation_generale/commands.py
ddd/admission/formation_generale/test/use_case/write/test_retyper_document_service.py
ddd/admission/formation_generale/use_case/write/retyper_document_service.py
ddd/admission/repository/i_emplacement_document.py
forms/admission/document.py
infrastructure/admission/formation_generale/handlers.py
infrastructure/admission/formation_generale/handlers_in_memory.py
infrastructure/admission/repository/emplacement_document.py
infrastructure/utils.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/document/document_detail.html
templates/admission/document/retype_form.html
templates/admission/document/retype_modal.html
tests/views/common/detail_tabs/test_document.py
views/autocomplete/document.py
views/common/detail_tabs/document.py

Pull request automatique de hotfix/OS-873 vers DEV

[hotfix/OS-873 => DEV] Back-office: Documents > Retypage d_un document (alias recatégorisation)

---

calendar/admission_calendar.py
ddd/admission/domain/service/i_titres_acces.py
ddd/admission/test/domain/service/test_calendrier_inscription.py

Pull request automatique de hotfix/OS-914 vers QA

[hotfix/OS-914 => QA] Front-office: Bug _Elements manquants_ à la confirmation pour les certificats > redéfinition d_un pot du calendrier

---

calendar/admission_calendar.py
ddd/admission/domain/service/i_titres_acces.py
ddd/admission/test/domain/service/test_calendrier_inscription.py

Pull request automatique de hotfix/OS-914 vers DEV

[hotfix/OS-914 => DEV] Front-office: Bug _Elements manquants_ à la confirmation pour les certificats > redéfinition d_un pot du calendrier

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/document/missing_documents.html
templates/admission/document/received_documents.html
templates/admission/document/uclouvain_documents.html

Pull request automatique de hotfix/OS-888 vers DEV

[hotfix/OS-888 => DEV] Back-office: Réclamation de documents > update de la regénération du dossier d_analyse

---

exports/admission_recap/admission_recap.py
exports/admission_recap/section.py
tests/exports/test_admission_recap.py

Pull request automatique de hotfix/OS-957 vers QA

[hotfix/OS-957 => QA] Back-office > Regénération du dossier d_analyse > Inclure les documents libres

---

exports/admission_recap/admission_recap.py
exports/admission_recap/section.py
tests/exports/test_admission_recap.py

Pull request automatique de hotfix/OS-957 vers DEV

[hotfix/OS-957 => DEV] Back-office > Regénération du dossier d_analyse > Inclure les documents libres

---

templates/admission/general_education/checklist.html

Pull request automatique de hotfix/OS-968 vers DEV

[hotfix/OS-968 => DEV] Back-office : Dans les onglets des expériences dans la checklist, les documents apparaissent en double

---

contrib/models/base.py
contrib/models/continuing_education.py
ddd/admission/formation_continue/dtos/proposition.py
ddd/admission/formation_continue/use_case/write/initier_proposition_service.py
ddd/admission/formation_continue/use_case/write/soumettre_proposition_service.py
ddd/admission/formation_continue/use_case/write/supprimer_proposition_service.py
infrastructure/admission/formation_continue/handlers.py
infrastructure/admission/formation_continue/handlers_in_memory.py
infrastructure/admission/formation_continue/repository/in_memory/proposition.py
infrastructure/admission/formation_continue/repository/proposition.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/continuing_education/includes/admission_status.html
templates/admission/continuing_education/tab_layout.html
templates/admission/general_education/tab_layout.html
tests/api/views/test_proposition.py
tests/api/views/test_submission.py
tests/api/views/test_training_choice.py
tests/commands/continuing_education/test_get_proposition_dto.py
tests/exports/test_admission_recap.py
tests/views/test_practical_information_url.py
utils.py
views/common/mixins.py
views/practical_information_url.py

Pull request automatique de feature/OS-452 vers DEV

[feature/OS-452 => DEV] Backoffice IUFC : En-tête d_une demande

---

contrib/models/base.py
ddd/admission/formation_continue/commands.py
ddd/admission/formation_continue/domain/service/i_lister_demandes.py
ddd/admission/formation_continue/dtos/liste.py
ddd/admission/formation_continue/test/use_case/read/test_lister_demandes_service.py
ddd/admission/formation_continue/use_case/read/lister_demandes_service.py
forms/__init__.py
forms/admission/filter.py
infrastructure/admission/formation_continue/domain/service/in_memory/lister_demandes.py
infrastructure/admission/formation_continue/domain/service/lister_demandes.py
infrastructure/admission/formation_continue/handlers.py
infrastructure/admission/formation_continue/handlers_in_memory.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
static/admission/admission.css
templates/admission/continuing_education/list.html
templates/admission/continuing_education/list_block.html
templates/admission/list/base_block.html
templates/admission/list/list_all_block.html
templatetags/admission.py
tests/views/autocomplete/test_trainings.py
tests/views/continuing_education/test_list.py
tests/views/test_excel_exports.py
tests/views/test_list.py
views/autocomplete/persons.py
views/autocomplete/trainings.py
views/continuing_education/details/checklist.py
views/excel_exports.py

Pull request automatique de feature/OS-526 vers DEV

[feature/OS-526 => DEV] En tant que gest. Parcours, je désire pouvoir filtrer les demandes d_inscription IUFC via un écran d_accès IUFC

---

views/general_education/details/checklist.py

…tion" > Ajout d'une icône représentant le caractère tardif de la demande

Fix OS-997: Back-office: type "Inscription" > Element "Choix de formation" > Ajout d'une icône représentant le caractère tardif de la demande

---

ddd/admission/formation_generale/domain/model/statut_checklist.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/general_education/includes/checklist/sic_decision_statuses.html

Pull request automatique de feature/OS-937 vers DEV

[feature/OS-937 => DEV] Back-office: Décision SIC > renommer l_état _à compléter_ en _suivi gestionnaire_

---

templates/admission/general_education/includes/checklist/fac_decision_approval_form.html

Pull request automatique de feature/OS-973 vers DEV

[feature/OS-973 => DEV] Back-office: Décision facultaire > Accord > Ajout du pictogramme étudiant à côté du label _Conditions complémentaires libres_

---

auth/roles/central_manager.py
auth/roles/program_manager.py
ddd/admission/formation_continue/commands.py
ddd/admission/formation_continue/domain/model/enums.py
ddd/admission/formation_continue/domain/model/proposition.py
ddd/admission/formation_continue/use_case/write/__init__.py
ddd/admission/formation_continue/use_case/write/completer_questions_specifiques_par_gestionnaire_service.py
forms/admission/coordonnees.py
forms/admission/specific_questions.py
infrastructure/admission/formation_continue/handlers.py
infrastructure/admission/formation_continue/handlers_in_memory.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/continuing_education/forms/specific_questions.html
templates/admission/general_education/forms/specific_questions.html
templatetags/admission.py
tests/views/common/detail_tabs/test_specific_questions.py
tests/views/common/form_tabs/test_coordonnees.py
tests/views/common/form_tabs/test_specific_questions.py
views/common/detail_tabs/specific_questions.py
views/common/form_tabs/coordonnees.py
views/common/form_tabs/specific_questions.py
views/common/mixins.py

Approved here : https://github.com/uclouvain/osis-admission/pull/1256

[OS-719] IUFC > Add the possibility to update the specificities of an admission

---

infrastructure/admission/formation_generale/domain/service/notification.py
mail_templates/checklist/general_education.py
migrations/0185_send_to_fac_mail_template_admission_type.py
templates/admission/checklist_state_button.html

Pull request automatique de feature/OS-1028 vers DEV

[feature/OS-1028 => DEV] Back-office: Décision de la faculté > Envoi de la demande en faculté > Adaptation d_un mot dans le contenu du mail

---

auth/predicates/common.py
auth/roles/central_manager.py
auth/roles/program_manager.py
forms/admission/checklist.py
templates/admission/document/document_detail.html
tests/views/common/detail_tabs/test_person.py
views/continuing_education/details/checklist/base.py

Pull request automatique de hotfix/OS-987 vers DEV

[hotfix/OS-987 => DEV] Problème de permission pour les utilisateurs étant gestionnaire du parcours étudiant et d_admission

---

forms/cdd_mail_template.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/config/cdd_mail_template_preview.html

Approved here : https://github.com/uclouvain/osis-admission/pull/1409

[OS-384] CDD configuration > fix a translation, change a label and add a cancel button

---

admin.py
infrastructure/admission/formation_generale/domain/service/pdf_generation.py
infrastructure/admission/repository/titre_acces_selectionnable.py
views/general_education/details/checklist.py

Pull request automatique de hotfix/OS-1063 vers DEV

[hotfix/OS-1063 => DEV] Back-office: type Inscription > Vues du parcours annualisé > Un candidat peut avoir plusieurs currints

---

auth/predicates/common.py
auth/roles/central_manager.py
auth/roles/program_manager.py
auth/roles/sic_management.py
contrib/models/base.py
contrib/models/epc_injection.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/general_education/includes/checklist/financabilite.html
templates/admission/general_education/tab_layout.html

Pull request automatique de feature/OS-1064 vers DEV

[feature/OS-1064 => DEV] Back-office: Lorsqu_une demande est passée en EPC, elle doit être en lecture seule

---

templates/admission/general_education/includes/checklist/financabilite.html

Pull request automatique de hotfix/OS-1127 vers DEV

[hotfix/OS-1127 => DEV] Il n_y a plus de calcule de financabilité _Proposition de l_algorithme de financabilité non calculée._

---

tasks/bulk_create_digit_persons_tickets.py

Pull request automatique de hotfix/OS-1132 vers MASTER

[hotfix/OS-1132 => MASTER] Appel à la validation ticket digit + fix financabilité

---

ddd/admission/domain/service/i_digit.py
ddd/admission/domain/validator/exceptions.py
infrastructure/admission/domain/service/digit.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OS-1135 vers MASTER

[WIP] [hotfix/OS-1135 => MASTER] [Création de compte] On ne peut pas soumettre le ticket à Digit si erreur syntaxique

---

ddd/admission/domain/service/i_digit.py
ddd/admission/domain/validator/exceptions.py
infrastructure/admission/domain/service/digit.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OS-1135 vers QA

[WIP] [hotfix/OS-1135 => QA] [Création de compte] On ne peut pas soumettre le ticket à Digit si erreur syntaxique

---

ddd/admission/domain/service/i_digit.py
ddd/admission/domain/validator/exceptions.py
infrastructure/admission/domain/service/digit.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OS-1135 vers DEV

[WIP] [hotfix/OS-1135 => DEV] [Création de compte] On ne peut pas soumettre le ticket à Digit si erreur syntaxique

---

infrastructure/admission/repository/digit.py
tasks/retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1145 vers MASTER

[WIP] [hotfix/OS-1145 => MASTER] [Ticket Status] Amélioration processus de récupération état ticket DigIT

---

infrastructure/admission/repository/digit.py

Pull request automatique de hotfix/OS-1138 vers MASTER

[WIP] [hotfix/OS-1138 => MASTER] [Compte DigIT] Utiliser le champ _sex_ OSIS pour envoyer à DigIT _genre_

---

infrastructure/admission/repository/digit.py
tasks/retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1145 vers QA

[WIP] [hotfix/OS-1145 => QA] [Ticket Status] Amélioration processus de récupération état ticket DigIT

---

infrastructure/admission/repository/digit.py

Pull request automatique de hotfix/OS-1138 vers QA

[WIP] [hotfix/OS-1138 => QA] [Compte DigIT] Utiliser le champ _sex_ OSIS pour envoyer à DigIT _genre_

---

infrastructure/admission/repository/digit.py
tasks/retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1145 vers DEV

[WIP] [hotfix/OS-1145 => DEV] [Ticket Status] Amélioration processus de récupération état ticket DigIT

---

infrastructure/admission/repository/digit.py

Pull request automatique de hotfix/OS-1138 vers DEV

[WIP] [hotfix/OS-1138 => DEV] [Compte DigIT] Utiliser le champ _sex_ OSIS pour envoyer à DigIT _genre_

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/modal_search_account.html
tests/views/common/form_tabs/test_person.py
views/services/search_account.py

Pull request automatique de hotfix/OS-1167 vers QA

[hotfix/OS-1167 => QA] [Ecran de fusion des comptes] Supprimer les boutons _Rejeter la fusion_/_Fusionner_ de l_onglet Données personelles

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/modal_search_account.html
tests/views/common/form_tabs/test_person.py
views/services/search_account.py

Pull request automatique de hotfix/OS-1167 vers MASTER

[hotfix/OS-1167 => MASTER] [Ecran de fusion des comptes] Supprimer les boutons _Rejeter la fusion_/_Fusionner_ de l_onglet Données personelles

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/modal_search_account.html
tests/views/common/form_tabs/test_person.py
views/services/search_account.py

Pull request automatique de hotfix/OS-1167 vers DEV

[hotfix/OS-1167 => DEV] [Ecran de fusion des comptes] Supprimer les boutons _Rejeter la fusion_/_Fusionner_ de l_onglet Données personelles

---

infrastructure/admission/domain/service/digit.py
infrastructure/admission/domain/service/lister_toutes_demandes.py

Pull request automatique de hotfix/OS-1170 vers QA

[WIP] [hotfix/OS-1170 => QA] [Affichage des demandes] La recherche par Noma ne fonctionne pas 

---

infrastructure/admission/domain/service/digit.py
infrastructure/admission/formation_generale/repository/proposition.py
tasks/retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1171 vers QA

[WIP] [hotfix/OS-1171 => QA] [Création des comptes] Impossible de soumettre un ticket DiGIT si déjà une demande refusée.

---

forms/admission/person.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OS-1172 vers QA

[WIP] [hotfix/OS-1172 => QA] Permettre à un gestionnaire de modifier des infos de signaletiques si compte temporaire

---

ddd/admission/events.py
infrastructure/admission/event_handler/reagir_proposition_fusion_defaite.py
infrastructure/admission/formation_generale/handlers.py
infrastructure/admission/handlers.py
templates/admission/previous_experience.html
views/services/previous_experience.py

Pull request automatique de hotfix/OS-1165 vers QA

[WIP] [hotfix/OS-1165 => QA] [Ecran de fusion] Rendre plus clair le fait qu_on prend les études secondaires du candidat

---

infrastructure/admission/repository/proposition_fusion_personne.py

Pull request automatique de hotfix/OS-1173 vers QA

[WIP] [hotfix/OS-1173 => QA] [Gestion des nomas] Réutiliser le noma retournée par DigIT

---

forms/admission/person.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OS-1172 vers MASTER

[WIP] [hotfix/OS-1172 => MASTER] Permettre à un gestionnaire de modifier des infos de signaletiques si compte temporaire

---

infrastructure/admission/repository/proposition_fusion_personne.py

Pull request automatique de hotfix/OS-1173 vers MASTER

[WIP] [hotfix/OS-1173 => MASTER] [Gestion des nomas] Réutiliser le noma retournée par DigIT

---

infrastructure/admission/formation_generale/repository/proposition.py
tasks/retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1171 vers MASTER

[hotfix/OS-1171 => MASTER] [Création des comptes] Impossible de soumettre un ticket DiGIT si déjà une demande refusée.

---

infrastructure/admission/domain/service/lister_toutes_demandes.py

Pull request automatique de hotfix/OS-1170 vers MASTER

[hotfix/OS-1170 => MASTER] [Affichage des demandes] La recherche par Noma ne fonctionne pas 

---

ddd/admission/events.py
infrastructure/admission/event_handler/reagir_proposition_fusion_defaite.py
infrastructure/admission/formation_generale/handlers.py
infrastructure/admission/handlers.py
templates/admission/previous_experience.html
views/services/previous_experience.py

Pull request automatique de hotfix/OS-1165 vers MASTER

[hotfix/OS-1165 => MASTER] [Ecran de fusion] Rendre plus clair le fait qu_on prend les études secondaires du candidat

---

infrastructure/admission/domain/service/digit.py
infrastructure/admission/domain/service/lister_toutes_demandes.py

Pull request automatique de hotfix/OS-1170 vers DEV

[WIP] [hotfix/OS-1170 => DEV] [Affichage des demandes] La recherche par Noma ne fonctionne pas 

---

forms/admission/person.py
infrastructure/admission/domain/service/digit.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OS-1172 vers DEV

[WIP] [hotfix/OS-1172 => DEV] Permettre à un gestionnaire de modifier des infos de signaletiques si compte temporaire

---

infrastructure/admission/domain/service/digit.py
infrastructure/admission/repository/proposition_fusion_personne.py

Pull request automatique de hotfix/OS-1173 vers DEV

[hotfix/OS-1173 => DEV] [Gestion des nomas] Réutiliser le noma retournée par DigIT

---

infrastructure/admission/domain/service/digit.py
infrastructure/admission/formation_generale/repository/proposition.py
tasks/retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1171 vers DEV

[hotfix/OS-1171 => DEV] [Création des comptes] Impossible de soumettre un ticket DiGIT si déjà une demande refusée.

---

ddd/admission/events.py
infrastructure/admission/event_handler/reagir_proposition_fusion_defaite.py
infrastructure/admission/formation_generale/handlers.py
infrastructure/admission/handlers.py
templates/admission/previous_experience.html
views/services/previous_experience.py

Pull request automatique de hotfix/OS-1165 vers DEV

[WIP] [hotfix/OS-1165 => DEV] [Ecran de fusion] Rendre plus clair le fait qu_on prend les études secondaires du candidat

---

views/common/detail_tabs/coordonnees.py
views/common/detail_tabs/person.py

Reverts uclouvain/osis-admission#1583

Revert "[WIP] [feature/OS-1059 => DEV] Contexte Doctorat - Duplication des onglets “Données personnelles > Identification” et Coordonnées"

---

views/common/detail_tabs/coordonnees.py
views/common/detail_tabs/person.py

Reverts uclouvain/osis-admission#1698

[WIP] [feature/OS-1059 => DEV] Contexte Doctorat - Duplication des onglets “Données personnelles > Identification” et Coordonnées

---

infrastructure/admission/event_handler/reagir_a_approuver_proposition.py

Pull request automatique de hotfix/OS-1185 vers MASTER

[WIP] [hotfix/OS-1185 => MASTER] Impossible d_approuver l_admission/inscription SIC

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1187 vers MASTER

[WIP] [hotfix/OS-1187 => MASTER] [Retrieve Digit Tickets] Soucis lorsque plusieurs tickets sont créés pour une personne

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1187 vers QA

[WIP] [hotfix/OS-1187 => QA] [Retrieve Digit Tickets] Soucis lorsque plusieurs tickets sont créés pour une personne

---

auth/predicates/common.py
auth/roles/central_manager.py
auth/roles/program_manager.py
tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1187 vers DEV

[WIP] [hotfix/OS-1187 => DEV] [Retrieve Digit Tickets] Soucis lorsque plusieurs tickets sont créés pour une personne

---

infrastructure/admission/repository/digit.py

Pull request automatique de hotfix/OS-1194 vers QA

[WIP] [hotfix/OS-1194 => QA] Modification endpoint DIGIT

---

infrastructure/admission/repository/digit.py
templates/admission/details/accounting.html
templates/admission/exports/recap/includes/accounting.html

Pull request automatique de hotfix/OS-1196 vers QA

[hotfix/OS-1196 => QA] Back-office > Onglet Comptabilité > L_information sur la carte de sport n_apparaît pas dans la vue de détails et le PDF

---

infrastructure/admission/repository/digit.py
templates/admission/details/accounting.html
templates/admission/exports/recap/includes/accounting.html

Pull request automatique de hotfix/OS-1196 vers DEV

[hotfix/OS-1196 => DEV] Back-office > Onglet Comptabilité > L_information sur la carte de sport n_apparaît pas dans la vue de détails et le PDF

---

infrastructure/admission/repository/digit.py

Pull request automatique de hotfix/OS-1194 vers MASTER

[WIP] [hotfix/OS-1194 => MASTER] Modification endpoint DIGIT

---

infrastructure/admission/repository/digit.py

Pull request automatique de hotfix/OS-1194 vers DEV

[WIP] [hotfix/OS-1194 => DEV] Modification endpoint DIGIT

---

infrastructure/admission/repository/digit.py

Pull request automatique de hotfix/OS-1201 vers MASTER

[WIP] [hotfix/OS-1201 => MASTER] Supprimer l_utilisation de last_registration_id

---

infrastructure/admission/domain/service/lister_toutes_demandes.py
views/common/mixins.py
views/general_education/details/checklist.py

Pull request automatique de hotfix/OS-1200 vers QA

[WIP] [hotfix/OS-1200 => QA] Ajouter une nouvelle condition pour l_injecter les demandes dans EPC

---

infrastructure/admission/domain/service/lister_toutes_demandes.py
infrastructure/admission/repository/digit.py
services/injection_epc/injection_dossier.py
views/common/mixins.py
views/general_education/details/checklist.py
views/services/epc_injection.py

Pull request automatique de hotfix/OS-1200 vers DEV

[WIP] [hotfix/OS-1200 => DEV] Ajouter une nouvelle condition pour l_injecter les demandes dans EPC

---

ddd/admission/commands.py
ddd/admission/domain/service/i_filtrer_toutes_demandes.py
ddd/admission/use_case/read/lister_demandes_service.py
forms/admission/filter.py
infrastructure/admission/domain/service/in_memory/lister_toutes_demandes.py
infrastructure/admission/domain/service/lister_toutes_demandes.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
services/injection_epc/injection_dossier.py
templates/admission/list/list_all.html
tests/views/test_excel_exports.py
tests/views/test_list.py
views/excel_exports.py

Pull request automatique de hotfix/OS-1168 vers DEV

[hotfix/OS-1168 => DEV] Back-office: Liste des demandes > Ajout d_un filtre avancé _Erreur d_injection_ concernant l_injection d_une demande dans EPC

---

ddd/admission/doctorat/preparation/test/use_case/write/test_recalculer_emplacements_documents_non_libres_proposition_service.py
ddd/admission/domain/service/reinitialiser_emplacements_documents_non_libres_proposition.py
ddd/admission/formation_continue/test/use_case/write/test_recalculer_emplacements_documents_non_libres_proposition_service.py
ddd/admission/formation_generale/test/use_case/write/test_recalculer_emplacements_documents_non_libres_proposition_service.py
ddd/admission/repository/i_emplacement_document.py
infrastructure/admission/repository/emplacement_document.py
infrastructure/admission/repository/in_memory/emplacement_document.py
tests/contrib/models/test_general.py

Pull request automatique de hotfix/OS-1208 vers MASTER

[WIP] [hotfix/OS-1208 => MASTER] Back-office: Adaptation de la commande pour nettoyer les documents qui ne sont plus pertinents

---

ddd/admission/doctorat/preparation/test/use_case/write/test_recalculer_emplacements_documents_non_libres_proposition_service.py
ddd/admission/domain/service/reinitialiser_emplacements_documents_non_libres_proposition.py
ddd/admission/formation_continue/test/use_case/write/test_recalculer_emplacements_documents_non_libres_proposition_service.py
ddd/admission/formation_generale/test/use_case/write/test_recalculer_emplacements_documents_non_libres_proposition_service.py
ddd/admission/repository/i_emplacement_document.py
infrastructure/admission/repository/emplacement_document.py
infrastructure/admission/repository/in_memory/emplacement_document.py
tests/contrib/models/test_general.py

Pull request automatique de hotfix/OS-1208 vers QA

[WIP] [hotfix/OS-1208 => QA] Back-office: Adaptation de la commande pour nettoyer les documents qui ne sont plus pertinents

---

forms/admission/person.py
tests/views/common/form_tabs/test_person.py

Pull request automatique de hotfix/OS-1207 vers DEV

[hotfix/OS-1207 => DEV] Back-office: Identification > L_enregistrement ne pourra se faire que lorsque tous les documents obligatoires seront présents

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1214 vers MASTER

[hotfix/OS-1214 => MASTER] Des champs manquent lors de la fusion d_un PersonMergeProposal vers une Person connue de OSIS 

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1214 vers DEV

[hotfix/OS-1214 => DEV] Des champs manquent lors de la fusion d_un PersonMergeProposal vers une Person connue de OSIS 

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1215 vers QA

[hotfix/OS-1215 => QA] La logique de fusion ne prend pas correctement en compte le cas des personnes connues dans OSIS

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1215 vers DEV

[hotfix/OS-1215 => DEV] La logique de fusion ne prend pas correctement en compte le cas des personnes connues dans OSIS

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1215 vers MASTER

[hotfix/OS-1215 => MASTER] La logique de fusion ne prend pas correctement en compte le cas des personnes connues dans OSIS

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1220 vers MASTER

[hotfix/OS-1220 => MASTER] La logique de fusion des CV ne garde pas les lignes du candidat automatiquement

---

forms/admission/person.py
templates/admission/document/document_detail.html
tests/views/autocomplete/test_document.py
tests/views/common/form_tabs/test_person.py
views/autocomplete/document.py
views/common/form_tabs/curriculum.py

Pull request automatique de hotfix/OS-1223 vers DEV

[hotfix/OS-1223 => DEV] Back-office: Annulation de l_obligation de fournir les documents obligatoires pour enregistrer

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1224 vers QA

[hotfix/OS-1224 => QA] Suppression d_adresse dans le cas d_une personne non connue dans OSIS

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1224 vers DEV

[hotfix/OS-1224 => DEV] Suppression d_adresse dans le cas d_une personne non connue dans OSIS

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

[hotfix/OS-1224 => MASTER] Suppression d_adresse dans le cas d_une personne non connue dans OSIS

---

ddd/admission/domain/service/i_digit.py
infrastructure/admission/formation_generale/repository/proposition.py

Pull request automatique de hotfix/OS-1225 vers DEV

[hotfix/OS-1225 => DEV] Les fusions d_admission non autorisée n_envoient pas de ticket de mise à jour à DigIT

---

ddd/admission/domain/service/i_digit.py
infrastructure/admission/formation_generale/repository/proposition.py

Pull request automatique de hotfix/OS-1225 vers QA

[hotfix/OS-1225 => QA] Les fusions d_admission non autorisée n_envoient pas de ticket de mise à jour à DigIT

---

ddd/admission/domain/service/i_digit.py
infrastructure/admission/formation_generale/repository/proposition.py

Pull request automatique de hotfix/OS-1225 vers MASTER

[hotfix/OS-1225 => MASTER] Les fusions d_admission non autorisée n_envoient pas de ticket de mise à jour à DigIT

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1226 vers QA

[hotfix/OS-1226 => QA] Les experiences ne sont pas valorisées dans le dossier d_admission lors de la fusion

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1226 vers DEV

[hotfix/OS-1226 => DEV] Les experiences ne sont pas valorisées dans le dossier d_admission lors de la fusion

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1226 vers MASTER

[hotfix/OS-1226 => MASTER] Les experiences ne sont pas valorisées dans le dossier d_admission lors de la fusion

---

infrastructure/admission/repository/proposition_fusion_personne.py
tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1228 vers QA

[hotfix/OS-1228 => QA] Les lignes de CV à supprimer ne sont pas supprimées dans EPC (via queue)

---

infrastructure/admission/repository/proposition_fusion_personne.py
tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1228 vers MASTER

[hotfix/OS-1228 => MASTER] Les lignes de CV à supprimer ne sont pas supprimées dans EPC (via queue)

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1229 vers MASTER

[hotfix/OS-1229 => MASTER] Les expériences académiques à supprimer ne sont pas correctement répercutées dans EPC lors de la fusion

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1229 vers QA

[hotfix/OS-1229 => QA] Les expériences académiques à supprimer ne sont pas correctement répercutées dans EPC lors de la fusion

---

views/services/previous_experience.py

Pull request automatique de hotfix/OS-1230 vers DEV

[hotfix/OS-1230 => DEV] Pas de CV à fusionner quand il n_y a que l_année des études secondaires fournie par le candidat

---

views/services/previous_experience.py

Pull request automatique de hotfix/OS-1230 vers MASTER

[hotfix/OS-1230 => MASTER] Pas de CV à fusionner quand il n_y a que l_année des études secondaires fournie par le candidat

---

views/services/previous_experience.py

Pull request automatique de hotfix/OS-1230 vers QA

[hotfix/OS-1230 => QA] Pas de CV à fusionner quand il n_y a que l_année des études secondaires fournie par le candidat

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1234 vers MASTER

[hotfix/OS-1234 => MASTER] Même problème avec les études secondaires

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1234 vers QA

[hotfix/OS-1234 => QA] Même problème avec les études secondaires

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1234 vers DEV

[hotfix/OS-1234 => DEV] Même problème avec les études secondaires

---

tasks/retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1236 vers MASTER

[hotfix/OS-1236 => MASTER] Pas d_admission_id fourni lors de l_injection dans EPC

---

tasks/retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1236 vers QA

[hotfix/OS-1236 => QA] Pas d_admission_id fourni lors de l_injection dans EPC

---

tasks/retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1236 vers DEV

[hotfix/OS-1236 => DEV] Pas d_admission_id fourni lors de l_injection dans EPC

---

infrastructure/admission/domain/service/digit.py

Pull request automatique de hotfix/OS-1237 vers MASTER

[hotfix/OS-1237 => MASTER] Les candidats connectés avec leur compte interne n_ont pas de NOMA associé dans le dossier d_admission

---

infrastructure/admission/domain/service/digit.py

Pull request automatique de hotfix/OS-1237 vers QA

[hotfix/OS-1237 => QA] Les candidats connectés avec leur compte interne n_ont pas de NOMA associé dans le dossier d_admission

---

contrib/models/epc_injection.py
infrastructure/admission/domain/service/profil_candidat.py
tests/views/common/form_tabs/curriculum/educational_experience_update/test_general.py
tests/views/common/form_tabs/curriculum/test_educational_experience_delete.py
tests/views/common/form_tabs/curriculum/test_non_educational_experience_delete.py
tests/views/common/form_tabs/curriculum/test_non_educational_experience_update.py
tests/views/common/form_tabs/test_education.py
views/common/form_tabs/curriculum.py
views/common/form_tabs/education.py

Pull request automatique de hotfix/OS-1231 vers QA

[hotfix/OS-1231 => QA] [Back-office] Une expérience du CV est considérée à tort comme une expérience EPC

---

contrib/models/epc_injection.py
infrastructure/admission/domain/service/profil_candidat.py
tests/views/common/form_tabs/curriculum/educational_experience_update/test_general.py
tests/views/common/form_tabs/curriculum/test_educational_experience_delete.py
tests/views/common/form_tabs/curriculum/test_non_educational_experience_delete.py
tests/views/common/form_tabs/curriculum/test_non_educational_experience_update.py
tests/views/common/form_tabs/test_education.py
views/common/form_tabs/curriculum.py
views/common/form_tabs/education.py

Pull request automatique de hotfix/OS-1231 vers DEV

[hotfix/OS-1231 => DEV] [Back-office] Une expérience du CV est considérée à tort comme une expérience EPC

---

ddd/admission/domain/service/i_digit.py
infrastructure/admission/domain/service/digit.py
infrastructure/admission/repository/digit.py

Pull request automatique de hotfix/OS-1251 vers MASTER

[hotfix/OS-1251 => MASTER] Déplacer logique de soumission de ticket DigIT pour les comptes internes

---

ddd/admission/doctorat/preparation/test/use_case/read/test_recuperer_documents_reclames_proposition_service.py
tasks/__init__.py
tasks/verifier_paiements_faits.py

Pull request automatique de hotfix/OS-1242 vers QA

[hotfix/OS-1242 => QA] Back-office: Frais de dossier > Tâche quotidienne pour débloquer les _Doit payer_ qui ont en réalité payé

---

ddd/admission/doctorat/preparation/test/use_case/read/test_recuperer_documents_reclames_proposition_service.py
tasks/__init__.py
tasks/verifier_paiements_faits.py

Pull request automatique de hotfix/OS-1242 vers DEV

[hotfix/OS-1242 => DEV] Back-office: Frais de dossier > Tâche quotidienne pour débloquer les _Doit payer_ qui ont en réalité payé

---

tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1255 vers MASTER

[WIP] [hotfix/OS-1255 => MASTER] Les fusions créent des doublons de PersonMergeProposal qui empêchent les futures fusions d_une même personne

---

locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/general_education/checklist.html
templates/admission/general_education/includes/checklist/financabilite_derogation_candidat_notifie_form.html

… and fix the financeability email sending.

[OS-1249] General checklist > hide the valuation button and change the related message 

---

ddd/admission/formation_generale/domain/model/enums.py
ddd/admission/formation_generale/repository/i_proposition.py
ddd/admission/use_case/write/soumettre_ticket_creation_personne.py
ddd/admission/use_case/write/valider_ticket_creation_personne.py
infrastructure/admission/formation_generale/handlers.py
infrastructure/admission/formation_generale/repository/in_memory/proposition.py
infrastructure/admission/formation_generale/repository/proposition.py
tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1262 vers DEV

[hotfix/OS-1262 => DEV] [Création du compte] La soumission du ticket DigIT lève une exception  AdmissionDansUnStatutPasAutoriseASInscrireException

---

ddd/admission/formation_generale/domain/model/enums.py
ddd/admission/formation_generale/repository/i_proposition.py
ddd/admission/use_case/write/soumettre_ticket_creation_personne.py
ddd/admission/use_case/write/valider_ticket_creation_personne.py
infrastructure/admission/formation_generale/handlers.py
infrastructure/admission/formation_generale/repository/in_memory/proposition.py
infrastructure/admission/formation_generale/repository/proposition.py
tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1262 vers QA

[hotfix/OS-1262 => QA] [Création du compte] La soumission du ticket DigIT lève une exception  AdmissionDansUnStatutPasAutoriseASInscrireException

---

ddd/admission/formation_generale/domain/model/enums.py
ddd/admission/formation_generale/repository/i_proposition.py
ddd/admission/use_case/write/soumettre_ticket_creation_personne.py
ddd/admission/use_case/write/valider_ticket_creation_personne.py
infrastructure/admission/formation_generale/handlers.py
infrastructure/admission/formation_generale/repository/in_memory/proposition.py
infrastructure/admission/formation_generale/repository/proposition.py
tasks/retrieve_digit_tickets_status.py
tests/tasks/test_retrieve_digit_tickets_status.py

Pull request automatique de hotfix/OS-1262 vers MASTER

[hotfix/OS-1262 => MASTER] [Création du compte] La soumission du ticket DigIT lève une exception  AdmissionDansUnStatutPasAutoriseASInscrireException

---

ddd/admission/doctorat/preparation/domain/model/proposition.py
ddd/admission/doctorat/preparation/test/use_case/write/test_approuver_admission_par_sic_service.py
ddd/admission/doctorat/preparation/test/use_case/write/test_approuver_inscription_par_sic_service.py
ddd/admission/domain/service/i_profil_candidat.py
ddd/admission/domain/service/profil_candidat.py
ddd/admission/domain/validator/_should_ne_pas_etre_en_quarantaine.py
ddd/admission/domain/validator/exceptions.py
ddd/admission/domain/validator/validator_by_business_action.py
ddd/admission/dtos/merge_proposal.py
ddd/admission/formation_continue/domain/model/proposition.py
ddd/admission/formation_continue/test/use_case/write/test_valider_proposition_service.py
ddd/admission/formation_continue/use_case/write/valider_proposition_service.py
ddd/admission/formation_generale/domain/model/proposition.py
ddd/admission/formation_generale/test/use_case/write/test_approuver_admission_par_sic_service.py
infrastructure/admission/domain/service/in_memory/profil_candidat.py
infrastructure/admission/domain/service/profil_candidat.py
infrastructure/admission/formation_continue/handlers.py
infrastructure/admission/formation_continue/handlers_in_memory.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OS-1273 vers MASTER

[hotfix/OS-1273 => MASTER] Back-office : Décision SIC > Autorisation & Demandes en quarantaine : correction du critère de quarantaine

---

ddd/admission/doctorat/preparation/domain/model/proposition.py
ddd/admission/doctorat/preparation/test/use_case/write/test_approuver_admission_par_sic_service.py
ddd/admission/doctorat/preparation/test/use_case/write/test_approuver_inscription_par_sic_service.py
ddd/admission/domain/service/i_profil_candidat.py
ddd/admission/domain/service/profil_candidat.py
ddd/admission/domain/validator/_should_ne_pas_etre_en_quarantaine.py
ddd/admission/domain/validator/exceptions.py
ddd/admission/domain/validator/validator_by_business_action.py
ddd/admission/dtos/merge_proposal.py
ddd/admission/formation_continue/domain/model/proposition.py
ddd/admission/formation_continue/test/use_case/write/test_valider_proposition_service.py
ddd/admission/formation_continue/use_case/write/valider_proposition_service.py
ddd/admission/formation_generale/domain/model/proposition.py
ddd/admission/formation_generale/test/use_case/write/test_approuver_admission_par_sic_service.py
infrastructure/admission/domain/service/in_memory/profil_candidat.py
infrastructure/admission/domain/service/profil_candidat.py
infrastructure/admission/formation_continue/handlers.py
infrastructure/admission/formation_continue/handlers_in_memory.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
services/injection_epc/injection_signaletique.py
tasks/verifier_paiements_faits.py

Pull request automatique de hotfix/OS-1273 vers QA

[hotfix/OS-1273 => QA] Back-office : Décision SIC > Autorisation & Demandes en quarantaine : correction du critère de quarantaine

---

ddd/admission/doctorat/preparation/domain/model/proposition.py
ddd/admission/doctorat/preparation/test/use_case/write/test_approuver_admission_par_sic_service.py
ddd/admission/doctorat/preparation/test/use_case/write/test_approuver_inscription_par_sic_service.py
ddd/admission/domain/service/i_profil_candidat.py
ddd/admission/domain/service/profil_candidat.py
ddd/admission/domain/validator/_should_ne_pas_etre_en_quarantaine.py
ddd/admission/domain/validator/exceptions.py
ddd/admission/domain/validator/validator_by_business_action.py
ddd/admission/dtos/merge_proposal.py
ddd/admission/formation_continue/domain/model/proposition.py
ddd/admission/formation_continue/test/use_case/write/test_valider_proposition_service.py
ddd/admission/formation_continue/use_case/write/valider_proposition_service.py
ddd/admission/formation_generale/domain/model/proposition.py
ddd/admission/formation_generale/test/use_case/write/test_approuver_admission_par_sic_service.py
infrastructure/admission/domain/service/in_memory/profil_candidat.py
infrastructure/admission/domain/service/profil_candidat.py
infrastructure/admission/formation_continue/handlers.py
infrastructure/admission/formation_continue/handlers_in_memory.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
services/injection_epc/injection_signaletique.py
tasks/verifier_paiements_faits.py

Pull request automatique de hotfix/OS-1273 vers DEV

[hotfix/OS-1273 => DEV] Back-office : Décision SIC > Autorisation & Demandes en quarantaine : correction du critère de quarantaine

---

templates/admission/general_education/includes/checklist/parcours.html
tests/views/doctorate/cdd/test_list.py

[hotfix/OS-1291 => MASTER] Back-office: Vues du parcours annualisé > Currint : Lignes manquantes

---

templates/admission/general_education/includes/checklist/parcours.html

Pull request automatique de hotfix/OS-1291 vers QA

[hotfix/OS-1291 => QA] Back-office: Vues du parcours annualisé > Currint : Lignes manquantes

---

ddd/admission/formation_generale/commands.py
ddd/admission/formation_generale/domain/model/proposition.py
ddd/admission/formation_generale/test/use_case/write/test_modifier_checklist_choix_formation_service.py
ddd/admission/formation_generale/use_case/write/modifier_checklist_choix_formation_service.py
forms/admission/checklist.py
templates/admission/general_education/includes/checklist/choix_formation_detail.html
templates/admission/general_education/includes/checklist/choix_formation_form.html
tests/views/general_education/checklist/test_choix_formation.py
views/general_education/details/checklist.py

Pull request automatique de hotfix/OS-1293 vers QA

[hotfix/OS-1293 => QA] Back-office : Choix de formation > Ajout d_un switch gérant le flag tardif

---

services/injection_epc/injection_dossier.py

Pull request automatique de hotfix/OS-1294 vers QA

[WIP] [hotfix/OS-1294 => QA] Dans l_injection des demandes, il faut envoie que le client SAP venait d_OSIS (pas envoyé celui de _SYNCHRO_)

---

api/views/autocomplete.py
calendar/admission_calendar.py
contrib/models/base.py
ddd/admission/doctorat/preparation/domain/service/verifier_proposition.py
ddd/admission/doctorat/preparation/test/domain/service/test_verifier_proposition.py
ddd/admission/doctorat/preparation/test/factory/doctorat.py
ddd/admission/doctorat/preparation/test/use_case/write/test_soumettre_proposition_service.py
ddd/admission/doctorat/preparation/use_case/read/determiner_annee_academique_et_pot_service.py
ddd/admission/domain/model/enums/condition_acces.py
ddd/admission/domain/service/i_titres_acces.py
ddd/admission/test/domain/service/test_calendrier_inscription.py
forms/doctorate/cdd/filter.py
infrastructure/admission/doctorat/preparation/domain/service/doctorat.py
infrastructure/admission/domain/service/annee_inscription_formation.py
management/commands/initialize_specific_questions.py
tests/api/views/autocomplete/test_training.py
tests/factories/doctorate.py
tests/templatetags/test_admission.py
tests/views/admin/test_initialize_specific_questions.py
tests/views/autocomplete/test_doctorate_trainings.py
tests/views/doctorate/checklist/test_past_experiences.py
tests/views/general_education/checklist/test_past_experiences.py
tests/views/test_excel_exports.py
utils.py

[feature/OS-1301 => DEV] Admission doctorat : utilisation des types FORMATION_PHD plutôt que PHD

---

admission_utils/list.py
infrastructure/admission/doctorat/preparation/domain/service/in_memory/lister_demandes.py
infrastructure/admission/doctorat/preparation/domain/service/lister_demandes.py
infrastructure/admission/domain/service/in_memory/lister_toutes_demandes.py
infrastructure/admission/domain/service/lister_toutes_demandes.py
infrastructure/admission/formation_continue/domain/service/in_memory/lister_demandes.py
infrastructure/admission/formation_continue/domain/service/lister_demandes.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/tab_layout.html
tests/utils/test_list.py
tests/views/test_list.py
tests/views/test_paginated_list.py
views/__init__.py
views/common/mixins.py
views/continuing_education/list.py
views/list.py
views/redirect.py

[feature/OS-1244 => DEV] Back-office: Liste des demandes > Demande courante > Ajout de boutons previous/next dans l_en-tête de la demande

---

migrations/0227_auto_20241024_0937.py

`get_or_create` à la place de `get`

Fix d'une migration pour la créations from scratch de la DB

---

templates/admission/list/base.html
views/list.py

Pull request automatique de hotfix/OS-1337 vers DEV

[hotfix/OS-1337 => DEV] Back-office: Liste des demandes > Liste de travail _personnalisée_ : par défaut ni _inclure_ ni _exclure_ ne sont sélectionnés

---

requirements.txt
tasks/injecter_dossier_a_epc.py
templates/admission/continuing_education/tab_layout.html
views/common/mixins.py

Pull request automatique de feature/OS-1414 vers DEV

[WIP] [feature/OS-1414 => DEV] Injection des demandes IUFC

---

templatetags/admission.py

OSIS: https://github.com/uclouvain/osis/pull/18738

[QA] Fix gestion des comptes

---

api/views/submission.py
ddd/admission/formation_continue/use_case/write/soumettre_proposition_service.py
infrastructure/admission/formation_continue/handlers.py
infrastructure/admission/formation_continue/handlers_in_memory.py
tests/api/views/test_submission.py
tests/exports/test_export_pdf.py
tests/views/general_education/checklist/sic_decision/test_approval.py

Pull request automatique de hotfix/OS-1432 vers QA

[hotfix/OS-1432 => QA] IUFC : le lien vers le pdf renseigné dans le mail du candidat doit afficher les infos de CV

---

api/views/submission.py
ddd/admission/formation_continue/use_case/write/soumettre_proposition_service.py
infrastructure/admission/formation_continue/handlers.py
infrastructure/admission/formation_continue/handlers_in_memory.py
tests/api/views/test_submission.py
tests/exports/test_export_pdf.py

Pull request automatique de hotfix/OS-1432 vers DEV

[hotfix/OS-1432 => DEV] IUFC : le lien vers le pdf renseigné dans le mail du candidat doit afficher les infos de CV

---

ddd/admission/domain/service/i_elements_confirmation.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OS-1420 vers QA

[hotfix/OS-1420 => QA] IUFC : onglet finalisation, faute dans le texte

---

ddd/admission/domain/service/i_elements_confirmation.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po

Pull request automatique de hotfix/OS-1420 vers DEV

[hotfix/OS-1420 => DEV] IUFC : onglet finalisation, faute dans le texte

---

ddd/admission/domain/service/i_calendrier_inscription.py
ddd/admission/formation_generale/domain/service/i_paiement_frais_dossier.py
ddd/admission/formation_generale/test/factory/proposition.py
ddd/admission/formation_generale/test/use_case/write/test_specifier_paiement_va_etre_ouvert_par_candidat_service.py
ddd/admission/formation_generale/use_case/write/specifier_paiement_va_etre_ouvert_par_candidat_service.py
infrastructure/admission/domain/service/calendrier_inscription.py
infrastructure/admission/domain/service/in_memory/calendrier_inscription.py
infrastructure/admission/formation_generale/repository/in_memory/proposition.py
tests/api/views/test_payment.py
tests/factories/general_education.py

Pull request automatique de hotfix/OS-1465 vers QA

[WIP] [hotfix/OS-1465 => QA] Bloquer le paiement de frais dossier en tenant compte le deadline du pot

---

models/base.py

Pull request automatique de hotfix/OS-1427 vers DEV

[hotfix/OS-1427 => DEV] Affichage _Noma inconnu_ alors que la personne a un noma dans base_student 

---

admission_utils/admission_program_managers_names.py
ddd/admission/doctorat/preparation/domain/service/i_historique.py
ddd/admission/doctorat/preparation/domain/service/i_notification.py
ddd/admission/doctorat/preparation/use_case/write/modifier_authentification_experience_parcours_anterieur_service.py
infrastructure/admission/doctorat/preparation/domain/service/historique.py
infrastructure/admission/doctorat/preparation/domain/service/in_memory/historique.py
infrastructure/admission/doctorat/preparation/domain/service/in_memory/notification.py
infrastructure/admission/doctorat/preparation/domain/service/notification.py
infrastructure/admission/doctorat/preparation/handlers.py
infrastructure/admission/doctorat/preparation/handlers_in_memory.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
mail_templates/checklist/doctorate.py
mail_templates/document.py
mail_templates/signatures.py
mail_templates/submission.py
tests/utils/test_get_admission_program_managers_names.py
tests/utils/test_salutation_prefix.py
utils.py
views/common/detail_tabs/documents.py
views/common/mixins.py
views/doctorate/details/checklist/base.py
views/doctorate/details/checklist/cdd_decision.py
views/doctorate/details/checklist/financeability.py
views/doctorate/details/checklist/projet_recherche.py
views/doctorate/details/checklist/sic_decision.py

Pull request automatique de hotfix/OS-1494 vers QA

[hotfix/OS-1494 => QA] Template mail doctorat modifications

---

ddd/admission/enums/emplacement_document.py
forms/admission/doctorate/project.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/doctorate/details/project.html
templates/admission/doctorate/forms/project.html
templates/admission/doctorate/includes/checklist/projet_recherche_detail.html
templates/admission/exports/recap/includes/project.html

Pull request automatique de hotfix/OS-1506 vers DEV

[hotfix/OS-1506 => DEV] Doctorat Admission : onglet Recherche - Modification intitulés de documents

---

api/views/autocomplete.py
infrastructure/admission/doctorat/preparation/domain/service/membre_CA.py
infrastructure/admission/doctorat/preparation/domain/service/promoteur.py
infrastructure/admission/doctorat/preparation/repository/groupe_de_supervision.py
tests/api/views/autocomplete/test_person.py
tests/api/views/test_supervision.py
tests/factories/person.py
tests/views/doctorate/forms/test_supervision.py
views/autocomplete/persons.py

Pull request automatique de hotfix/OS-1510 vers DEV

[hotfix/OS-1510 => DEV] Doctorat admission : problème pour ajouter un membre du CA pas encore user

---

api/schema.py
api/serializers/project.py
schema.yml

Pull request automatique de hotfix/OS-1547 vers QA

[hotfix/OS-1547 => QA] Admission doctorat : bug avec un titre de projet > 255 caractères

---

api/schema.py
api/serializers/project.py
schema.yml

Pull request automatique de hotfix/OS-1547 vers DEV

[hotfix/OS-1547 => DEV] Admission doctorat : bug avec un titre de projet > 255 caractères

---

templates/admission/continuing_education/includes/checklist/decision.html
templates/admission/details/coordonnees_backoffice.html
templates/admission/details/person_backoffice.html
templates/admission/doctorate/checklist.html
templates/admission/general_education/checklist.html
tests/views/cdd/test_list.py
tests/views/doctorate/cdd/test_list.py

Pull request automatique de hotfix/OS-1508 vers DEV

[hotfix/OS-1508 => DEV] Doctorat admission - Gestionnaire CDD bloqué quand doublon trouvé

---

ddd/admission/doctorat/preparation/commands.py
ddd/admission/doctorat/preparation/domain/service/i_lister_demandes.py
ddd/admission/doctorat/preparation/dtos/liste.py
ddd/admission/doctorat/preparation/use_case/read/lister_demandes_service.py
infrastructure/admission/doctorat/preparation/domain/service/in_memory/lister_demandes.py
infrastructure/admission/doctorat/preparation/domain/service/lister_demandes.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/doctorate/cdd/list_block.html
tests/views/doctorate/cdd/test_list.py
tests/views/test_excel_exports.py
views/excel_exports.py

Pull request automatique de hotfix/OS-1524 vers DEV

[hotfix/OS-1524 => DEV] Admission doctorat Excel - Rajouter qlq champs

---

ddd/admission/doctorat/preparation/domain/model/proposition.py
ddd/admission/doctorat/preparation/domain/validator/__init__.py
ddd/admission/doctorat/preparation/domain/validator/_should_informations_checklist_etre_completees.py
ddd/admission/doctorat/preparation/domain/validator/exceptions.py
ddd/admission/doctorat/preparation/domain/validator/validator_by_business_action.py
ddd/admission/doctorat/preparation/test/factory/proposition.py
ddd/admission/doctorat/preparation/test/use_case/write/test_approuver_admission_par_sic_service.py
ddd/admission/doctorat/preparation/test/use_case/write/test_approuver_inscription_par_sic_service.py
ddd/admission/doctorat/preparation/test/use_case/write/test_specifier_informations_acceptation_proposition_par_sic_service.py
locale/en/LC_MESSAGES/django.po
locale/fr_BE/LC_MESSAGES/django.po
templates/admission/doctorate/includes/checklist/sic_decision_statuses.html
templates/admission/general_education/includes/checklist/sic_decision_approval_panel.html
tests/views/continuing_education/checklist/test_decision.py
tests/views/doctorate/checklist/sic_decision/test_approval.py
tests/views/doctorate/checklist/sic_decision/test_approval_final.py

Pull request automatique de hotfix/OS-1613 vers DEV

[hotfix/OS-1613 => DEV] Admission doctorat - ne pas permettre à SIC d_autoriser à inscrire si la CDD n_a pas accepté la demande

---

exports/admission_recap/attachments.py
tasks/generate_admission_folder.py

Pull request automatique de hotfix/OS-1599 vers DEV

[hotfix/OS-1599 => DEV] Admission > Doctorat : problème de génération du récapitulatif après réclamation des documents

---

api/schema.py
api/serializers/supervision.py
schema.yml
templates/admission/doctorate/details/supervision.html
tests/api/views/autocomplete/test_person.py
views/autocomplete/persons.py

Pull request automatique de hotfix/OS-1606 vers DEV

[hotfix/OS-1606 => DEV] Admission doctorat, un promoteur ne voit pas sa candidate dans la liste des candidats :
